apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sonataflow.yaml
configMapGenerator:
  - name: llm-tool-agent-resources
    files:
      - agent-loop.sw.yaml=../src/main/resources/agent-loop.sw.yaml
      - tool-executor.sw.yaml=../src/main/resources/tool-executor.sw.yaml
