apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sonataflow.yaml
configMapGenerator:
  - name: llm-tool-agent-resources
    files:
      - agent-loop.sw.yaml=../src/main/resources/sub_flows/agent-loop.sw.yaml
      - tool-executor.sw.yaml=../src/main/resources/sub_flows/tool-executor.sw.yaml
      - boolean-decision.sw.yaml=../src/main/resources/sub_flows/boolean-decision.sw.yaml
      - choice-decision.sw.yaml=../src/main/resources/sub_flows/choice-decision.sw.yaml
